-- CMS migration for the existing Supabase project.
-- Run after supabase-schema.sql. Safe to run more than once.

create table if not exists public.pages (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    status text not null default 'published' check (status in ('draft', 'published')),
    content jsonb not null default '{}'::jsonb,
    published_at timestamptz,
    updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_projects (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null default '',
    category text not null default '',
    client_name text not null default '',
    project_date date,
    project_url text not null default '',
    image_url text not null default '',
    video_url text not null default '',
    status text not null default 'published' check (status in ('draft', 'published')),
    is_featured boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.seo_settings (
    id bigint generated by default as identity primary key,
    page_slug text not null unique,
    title text not null default '',
    description text not null default '',
    keywords text not null default '',
    canonical_url text not null default '',
    og_image_url text not null default '',
    favicon_url text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.navigation_items (
    id bigint generated by default as identity primary key,
    label text not null,
    url text not null,
    location text not null default 'header',
    sort_order integer not null default 0,
    is_visible boolean not null default true,
    updated_at timestamptz not null default now()
);

create table if not exists public.content_revisions (
    id bigint generated by default as identity primary key,
    entity_type text not null,
    entity_id bigint not null,
    payload jsonb not null default '{}'::jsonb,
    status text not null default 'draft' check (status in ('draft', 'published')),
    created_by uuid references auth.users(id),
    created_at timestamptz not null default now()
);

alter table public.pages enable row level security;
alter table public.portfolio_projects enable row level security;
alter table public.seo_settings enable row level security;
alter table public.navigation_items enable row level security;
alter table public.content_revisions enable row level security;

drop policy if exists "public can read published pages" on public.pages;
create policy "public can read published pages" on public.pages for select to anon, authenticated using (status = 'published' or (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');
drop policy if exists "owner can manage pages" on public.pages;
create policy "owner can manage pages" on public.pages for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "public can read published projects" on public.portfolio_projects;
create policy "public can read published projects" on public.portfolio_projects for select to anon, authenticated using (status = 'published' or (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');
drop policy if exists "owner can manage projects" on public.portfolio_projects;
create policy "owner can manage projects" on public.portfolio_projects for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "public can read seo" on public.seo_settings;
create policy "public can read seo" on public.seo_settings for select to anon, authenticated using (true);
drop policy if exists "owner can manage seo" on public.seo_settings;
create policy "owner can manage seo" on public.seo_settings for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "public can read visible navigation" on public.navigation_items;
create policy "public can read visible navigation" on public.navigation_items for select to anon, authenticated using (is_visible = true or (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');
drop policy if exists "owner can manage navigation" on public.navigation_items;
create policy "owner can manage navigation" on public.navigation_items for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "owner can manage revisions" on public.content_revisions;
create policy "owner can manage revisions" on public.content_revisions for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

insert into public.pages (slug, title, status, content, published_at)
values
('home', 'الرئيسية', 'published', '{"source":"index.html"}'::jsonb, now()),
('about', 'من أنا', 'published', '{"source":"pages/about.html"}'::jsonb, now()),
('services', 'الخدمات والباقات', 'published', '{"source":"pages/editing-packages.html"}'::jsonb, now()),
('contact', 'تواصل معي', 'published', '{"source":"index.html#contact"}'::jsonb, now())
on conflict (slug) do nothing;

insert into public.portfolio_projects (title, description, category, project_url, image_url, sort_order)
select seed.title, seed.description, seed.category, seed.project_url, seed.image_url, seed.sort_order
from (values
('إعلان تجاري احترافي', 'مشروع إعلاني متكامل مع مؤثرات وموسيقى', 'promo', 'https://www.behance.net/gallery/236027327/reel-islamgroub-marketing-agency-egypet', 'assets/images/1159372.png', 10),
('مقدمة فيديو احترافية', 'مقدمة جميلة بمؤثرات 3D وحركات احترافية', 'intro', 'https://www.behance.net/gallery/244733517/For-an-English-courses-company', 'assets/images/تحرير-الفديو.png', 20),
('مونتاج فيديو متقدم', 'تعديل احترافي مع انتقالات وتأثيرات بصرية', 'edit', 'https://www.behance.net/gallery/236021239/reel-wosoolnet-marketing-agency-saudia-AR', 'assets/images/أهمية-مونتاج-الفيديو.png', 30)
) as seed(title, description, category, project_url, image_url, sort_order)
where not exists (select 1 from public.portfolio_projects p where p.title = seed.title);

insert into public.seo_settings (page_slug, title, description, keywords, canonical_url)
values ('home', 'محمود مصطفى - مصمم فيديو واحترافي المونتاج', 'موقع محمود مصطفى لمونتاج الفيديو وتصميم المحتوى الإبداعي.', 'المونتاج, تصميم فيديو, محرر فيديو, فيديو احترافي', 'https://mahmoudmostafa.online/')
on conflict (page_slug) do nothing;

insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do nothing;

-- Public files can be viewed; only the authenticated owner can change them.
drop policy if exists "public can view site media" on storage.objects;
create policy "public can view site media" on storage.objects for select to anon, authenticated using (bucket_id = 'site-media');
drop policy if exists "owner can manage site media" on storage.objects;
create policy "owner can manage site media" on storage.objects for all to authenticated using (bucket_id = 'site-media' and (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check (bucket_id = 'site-media' and (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');
