create table if not exists public.visitors (
    id bigint generated by default as identity primary key,
    page text not null default '/',
    visited_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customer_email text,
    package_type text not null default 'باقة مخصصة',
    details text not null default '',
    budget numeric,
    status text not null default 'new' check (status in ('new', 'contacted', 'completed', 'cancelled')),
    created_at timestamptz not null default now()
);

alter table public.visitors enable row level security;
alter table public.orders enable row level security;

drop policy if exists "public can record visits" on public.visitors;
create policy "public can record visits"
on public.visitors for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read visits" on public.visitors;
create policy "owner can read visits"
on public.visitors for select
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
on public.orders for insert
to anon, authenticated
with check (true);

drop policy if exists "owner can read orders" on public.orders;
create policy "owner can read orders"
on public.orders for select
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "owner can update orders" on public.orders;
create policy "owner can update orders"
on public.orders for update
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

create table if not exists public.site_content (
    id bigint generated by default as identity primary key,
    content_type text not null check (content_type in ('setting', 'skill', 'portfolio', 'video', 'package', 'review')),
    title text not null,
    description text not null default '',
    category text not null default '',
    image_url text not null default '',
    icon text not null default '',
    rating smallint check (rating between 1 and 5),
    sort_order integer not null default 0,
    is_visible boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "public can read visible site content" on public.site_content;
create policy "public can read visible site content"
on public.site_content for select
to anon, authenticated
using (is_visible = true or (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "owner can insert site content" on public.site_content;
create policy "owner can insert site content"
on public.site_content for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "owner can update site content" on public.site_content;
create policy "owner can update site content"
on public.site_content for update
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com')
with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "owner can delete site content" on public.site_content;
create policy "owner can delete site content"
on public.site_content for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

create table if not exists public.site_settings (
    key text primary key,
    value jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.site_sections (
    id bigint generated by default as identity primary key,
    section_key text not null unique,
    title text not null,
    is_visible boolean not null default true,
    sort_order integer not null default 0,
    settings jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.media_assets (
    id bigint generated by default as identity primary key,
    name text not null,
    media_type text not null check (media_type in ('image', 'video', 'file')),
    url text not null,
    alt_text text not null default '',
    created_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;
alter table public.site_sections enable row level security;
alter table public.media_assets enable row level security;

drop policy if exists "public can read site settings" on public.site_settings;
create policy "public can read site settings" on public.site_settings for select to anon, authenticated using (true);
drop policy if exists "owner can manage site settings" on public.site_settings;
create policy "owner can manage site settings" on public.site_settings for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "public can read visible sections" on public.site_sections;
create policy "public can read visible sections" on public.site_sections for select to anon, authenticated using (is_visible = true or (auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');
drop policy if exists "owner can manage sections" on public.site_sections;
create policy "owner can manage sections" on public.site_sections for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

drop policy if exists "owner can read media" on public.media_assets;
create policy "owner can read media" on public.media_assets for select to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');
drop policy if exists "owner can manage media" on public.media_assets;
create policy "owner can manage media" on public.media_assets for all to authenticated using ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com') with check ((auth.jwt() ->> 'email') = 'mahmoud339sa@gmail.com');

insert into public.site_content (content_type, title, description, category, sort_order, is_visible)
select 'skill', seed.title, seed.description, 'خدمات', seed.sort_order, true
from (values
    ('مونتاج احترافي', 'تحرير فيديو متكامل مناسب للإعلانات والسوشيال ميديا واليوتيوب.', 10),
    ('تصميم فيديو', 'تصميم بصري حديث يحول الفكرة إلى فيديو واضح وجذاب.', 20),
    ('إعلانات سوشيال ميديا', 'فيديوهات قصيرة عالية التأثير ومناسبة لمنصات التواصل.', 30),
    ('مقدمات بصرية', 'مقدمات وحركات بصرية تمنح المحتوى هوية مميزة.', 40)
) as seed(title, description, sort_order)
where not exists (select 1 from public.site_content existing where existing.content_type = 'skill' and existing.title = seed.title);

insert into public.site_content (content_type, title, description, sort_order, is_visible)
select 'setting', seed.title, seed.description, 0, true
from (values
    ('previewGoal', 'تحويل الأفكار إلى فيديوهات قوية تجذب الانتباه وتزيد التفاعل.')
) as seed(title, description)
where not exists (select 1 from public.site_content existing where existing.content_type = 'setting' and existing.title = seed.title);

insert into public.site_content (content_type, title, description, category, image_url, sort_order, is_visible)
select 'portfolio', seed.title, seed.description, seed.category, seed.image_url, seed.sort_order, true
from (values
    ('إعلان تجاري احترافي', 'مشروع إعلاني متكامل مع مؤثرات وموسيقى.', 'promo', 'assets/images/1159372.png', 10),
    ('مقدمة فيديو احترافية', 'مقدمة جميلة بمؤثرات 3D وحركات احترافية.', 'intro', 'assets/images/تحرير-الفديو.png', 20),
    ('مونتاج فيديو متقدم', 'تعديل احترافي مع انتقالات وتأثيرات بصرية.', 'edit', 'assets/images/أهمية-مونتاج-الفيديو.png', 30)
) as seed(title, description, category, image_url, sort_order)
where not exists (select 1 from public.site_content existing where existing.content_type = 'portfolio' and existing.title = seed.title);

insert into public.site_content (content_type, title, description, category, rating, sort_order, is_visible)
select 'review', seed.title, seed.description, seed.category, 5, seed.sort_order, true
from (values
    ('أحمد مصطفى', 'التعامل كان ممتازًا والنتيجة طلعت أفضل من توقعاتي. الفيديو أصبح جاهزًا للنشر بشكل احترافي.', 'صانع محتوى', 10),
    ('سارة علي', 'سرعة في التنفيذ واهتمام بالتفاصيل. كل تعديل طلبته اتنفذ بدقة وبشكل جميل جدًا.', 'صاحبة مشروع', 20),
    ('محمد إبراهيم', 'مونتاج مميز وأفكار بصرية ساعدتني أظهر شغلي بصورة أقوى وأكثر احترافية.', 'مسوّق رقمي', 30),
    ('عبدالرحمن ثروت', 'شغل احترافي جدًا واهتمام بالتفاصيل من أول فكرة لحد التسليم النهائي.', 'صانع محتوى', 40),
    ('جمال', 'تسليم في الموعد وشغل على المستوى المهني. أكيد هنتعامل مرة ثانية.', 'صاحب مشروع', 50)
) as seed(title, description, category, sort_order)
where not exists (select 1 from public.site_content existing where existing.content_type = 'review' and existing.title = seed.title);

insert into public.site_content (content_type, title, description, category, sort_order, is_visible)
select 'package', seed.title, seed.description, seed.price, seed.sort_order, true
from (values
    ('الباقة الأساسية', 'للفيديوهات القصيرة والمحتوى السريع.', '4000 جنيه / فيديو', 10),
    ('الباقة الاحترافية', 'للسوشيال ميديا والإعلانات ذات التأثير القوي.', '7000 جنيه / فيديو', 20),
    ('باقة الشركات', 'حل متكامل للحملات والمحتوى المستمر.', '15000 جنيه / فيديو', 30)
) as seed(title, description, price, sort_order)
where not exists (select 1 from public.site_content existing where existing.content_type = 'package' and existing.title = seed.title);
